const reasons = {
    "adj": [
        "",
        "incompetent",
        "Web Scale",
        "Power Tripping",
        "production ready",
        "broken",
        "cash-hungry",
        "all-knowing",
        "multithreaded",
        "almighty",
        "Rust fork of",
        "decentralized",
        "desynced",
        "delayed",
        "unstable",
        "unreliable",
        "clickbait",
        "containerized",
        "new",
        "redundant",
        "highly-available",
        "selfhosted",
        "AWS Certified",
        "sharded",
        "banned",
        "undefined",
        "free trial of",
        "sponsor of today's video,",
        "dearrowed",
        "Web3.5",
        "latest beta of",
    ],
    "noun": [
        "developer",
        "Redis",
        "Postgres",
        "Kubernetes",
        "moderators",
        "Hetzner VPS",
        "Google",
        "YouTube redesign",
        "serverless infrastructure",
        "SponsorBlock DAO",
        "unknown perpetrator",
        "NodeJS",
        "Stackgres",
        "mirrors",
        "sponsors",
        "discord bot",
        "NTP sync",
        "uncaught promise",
        "CloudFlare",
        "replica",
        "artificial intelligence",
        "backend",
        "free VPS",
        "IPO",
        "discord server icon",
        "block storage",
        "systemd",
        "webhook",
        "mass submissions",
        "load balancer",
        "csv download",
        "title you wouldn't have clicked on",
        "thumbnail you wouldn't have clicked on",
        "@sponsorblock@fosstodon.org",
        "thumbnail that really wasn't that clickbait",
        "niche aggressive category",
        "funny jokes",
        "LTT pipeline",
        "SponsorBlock AI Summarization",
    ],
    "reason": [
        "ran out of memory",
        "turned off the server",
        "tripped on the power cord",
        "made all those segments on LTT",
        "fired the developer",
        "deleted the database",
        "bought out SponsorBlock",
        "deleted the microservices",
        "abused the API",
        "DDOSed the server",
        "deleted all the DNS records",
        "asked how many rq/s it gets",
        "didn't throw enough money at it",
        "wasn't decentralized",
        "used 100% CPU",
        "threw an uncaught promise",
        "expected JSON",
        "could not read properties of undefined",
        "responded with a status of 503",
        "only listened on IPv6",
        "turned everything into FillerPlus",
        "deleted System32",
        "ran out of disk space",
        "reenabled the firewall",
        "wasn't written in Rust (video game)",
        "was taken down by Google",
        "was running as root",
        "timed out",
        "never existed",
        "wasn't open source",
        "will be fixed in 3 years",
        "wasn't a priority",
        "wasn't using arch, btw",
        "wasn't in a container",
        "was disabled for load reasons",
        "just stopped working",
        "got paywalled",
        "was blocked by Russia",
        "ran out of ChatGPT Plus credits",
        "ran out of SponsorBlockCoins",
        "touched grass",
        "wasn't pinned in #general",
        "was a good idea in theory, but in practice used by geeks",
        "wasn't clicked on by enough subscribers",
        "failed Halal certification",
        "used a shirk which is related to black magic",
        "solved all clickbait on youtube",
        "was replaced by a moderator with the exact same timings",
        "unionized",
        "hit that subscribe button",
    ],
    "global": [
        "[object Object]",
        "error: undefined",
        "Loading...",
        "SponsorBlock isn't down",
        "Activate Windows \n Go to Settings to activate Windows",
        "I'm sorry, but I cannot fulfill this request as it goes against OpenAI use policy",
        "Ad blockers are not allowed on YouTube\n It looks like you may be using an ad blocker.",
    ]
}